scoreboard players add @a xp 0
execute at @a[lm=0,l=0] run scoreboard players set @p xp 0
execute at @a[lm=1,l=1] run scoreboard players set @p xp 1 
execute at @a[lm=2,l=2] run scoreboard players set @p xp 2 
execute at @a[lm=3,l=3] run scoreboard players set @p xp 3 
execute at @a[lm=4,l=4] run scoreboard players set @p xp 4 
execute at @a[lm=5,l=5] run scoreboard players set @p xp 5 
execute at @a[lm=6,l=6] run scoreboard players set @p xp 6 
execute at @a[lm=7,l=7] run scoreboard players set @p xp 7 
execute at @a[lm=8,l=8] run scoreboard players set @p xp 8 
execute at @a[lm=9,l=9] run scoreboard players set @p xp 9 
execute at @a[lm=10,l=10] run scoreboard players set @p xp 10 
execute at @a[lm=11,l=11] run scoreboard players set @p xp 11 
execute at @a[lm=12,l=12] run scoreboard players set @p xp 12 
execute at @a[lm=13,l=13] run scoreboard players set @p xp 13 
execute at @a[lm=14,l=14] run scoreboard players set @p xp 14 
execute at @a[lm=15,l=15] run scoreboard players set @p xp 15 
execute at @a[lm=16,l=16] run scoreboard players set @p xp 16 
execute at @a[lm=17,l=17] run scoreboard players set @p xp 17 
execute at @a[lm=18,l=18] run scoreboard players set @p xp 18 
execute at @a[lm=19,l=19] run scoreboard players set @p xp 19 
execute at @a[lm=20,l=20] run scoreboard players set @p xp 20
execute at @a[lm=21,l=21] run scoreboard players set @p xp 21
execute at @a[lm=22,l=22] run scoreboard players set @p xp 22 
execute at @a[lm=23,l=23] run scoreboard players set @p xp 23 
execute at @a[lm=24,l=24] run scoreboard players set @p xp 24 
execute at @a[lm=25,l=25] run scoreboard players set @p xp 25 
execute at @a[lm=26,l=26] run scoreboard players set @p xp 26 
execute at @a[lm=27,l=27] run scoreboard players set @p xp 27 
execute at @a[lm=28,l=28] run scoreboard players set @p xp 28 
execute at @a[lm=29,l=29] run scoreboard players set @p xp 29 
execute at @a[lm=30,l=30] run scoreboard players set @p xp 30
execute at @a[lm=31,l=31] run scoreboard players set @p xp 31
execute at @a[lm=32,l=32] run scoreboard players set @p xp 32 
execute at @a[lm=33,l=33] run scoreboard players set @p xp 33 
execute at @a[lm=34,l=34] run scoreboard players set @p xp 34 
execute at @a[lm=35,l=35] run scoreboard players set @p xp 35 
execute at @a[lm=36,l=36] run scoreboard players set @p xp 36 
execute at @a[lm=37,l=37] run scoreboard players set @p xp 37 
execute at @a[lm=38,l=38] run scoreboard players set @p xp 38 
execute at @a[lm=39,l=39] run scoreboard players set @p xp 39 
execute at @a[lm=40,l=40] run scoreboard players set @p xp 40
execute at @a[lm=41,l=41] run scoreboard players set @p xp 41
execute at @a[lm=42,l=42] run scoreboard players set @p xp 42 
execute at @a[lm=43,l=43] run scoreboard players set @p xp 43 
execute at @a[lm=44,l=44] run scoreboard players set @p xp 44 
execute at @a[lm=45,l=45] run scoreboard players set @p xp 45 
execute at @a[lm=46,l=46] run scoreboard players set @p xp 46 
execute at @a[lm=47,l=47] run scoreboard players set @p xp 47 
execute at @a[lm=48,l=48] run scoreboard players set @p xp 48 
execute at @a[lm=49,l=49] run scoreboard players set @p xp 49 
execute at @a[lm=50,l=50] run scoreboard players set @p xp 50
execute at @a[lm=51,l=51] run scoreboard players set @p xp 51
execute at @a[lm=52,l=52] run scoreboard players set @p xp 52 
execute at @a[lm=53,l=53] run scoreboard players set @p xp 53 
execute at @a[lm=54,l=54] run scoreboard players set @p xp 54 
execute at @a[lm=55,l=55] run scoreboard players set @p xp 55 
execute at @a[lm=56,l=56] run scoreboard players set @p xp 56 
execute at @a[lm=57,l=57] run scoreboard players set @p xp 57 
execute at @a[lm=58,l=58] run scoreboard players set @p xp 58 
execute at @a[lm=59,l=59] run scoreboard players set @p xp 59 
execute at @a[lm=60,l=60] run scoreboard players set @p xp 60
execute at @a[lm=61,l=61] run scoreboard players set @p xp 61
execute at @a[lm=62,l=62] run scoreboard players set @p xp 62 
execute at @a[lm=63,l=63] run scoreboard players set @p xp 63 
execute at @a[lm=64,l=64] run scoreboard players set @p xp 64 
execute at @a[lm=65,l=65] run scoreboard players set @p xp 65 
execute at @a[lm=66,l=66] run scoreboard players set @p xp 66 
execute at @a[lm=67,l=67] run scoreboard players set @p xp 67 
execute at @a[lm=68,l=68] run scoreboard players set @p xp 68 
execute at @a[lm=69,l=69] run scoreboard players set @p xp 69 
execute at @a[lm=70,l=70] run scoreboard players set @p xp 70
execute at @a[lm=71,l=71] run scoreboard players set @p xp 71
execute at @a[lm=72,l=72] run scoreboard players set @p xp 72 
execute at @a[lm=73,l=73] run scoreboard players set @p xp 73 
execute at @a[lm=74,l=74] run scoreboard players set @p xp 74 
execute at @a[lm=75,l=75] run scoreboard players set @p xp 75 
execute at @a[lm=76,l=76] run scoreboard players set @p xp 76 
execute at @a[lm=77,l=77] run scoreboard players set @p xp 77 
execute at @a[lm=78,l=78] run scoreboard players set @p xp 78 
execute at @a[lm=79,l=79] run scoreboard players set @p xp 79 
execute at @a[lm=80,l=80] run scoreboard players set @p xp 80
execute at @a[lm=81,l=81] run scoreboard players set @p xp 81
execute at @a[lm=82,l=82] run scoreboard players set @p xp 82 
execute at @a[lm=83,l=83] run scoreboard players set @p xp 83 
execute at @a[lm=84,l=84] run scoreboard players set @p xp 84 
execute at @a[lm=85,l=85] run scoreboard players set @p xp 85 
execute at @a[lm=86,l=86] run scoreboard players set @p xp 86 
execute at @a[lm=87,l=87] run scoreboard players set @p xp 87 
execute at @a[lm=88,l=88] run scoreboard players set @p xp 88 
execute at @a[lm=89,l=89] run scoreboard players set @p xp 89 
execute at @a[lm=90,l=90] run scoreboard players set @p xp 90
execute at @a[lm=91,l=91] run scoreboard players set @p xp 91
execute at @a[lm=92,l=92] run scoreboard players set @p xp 92 
execute at @a[lm=93,l=93] run scoreboard players set @p xp 93 
execute at @a[lm=94,l=94] run scoreboard players set @p xp 94 
execute at @a[lm=95,l=95] run scoreboard players set @p xp 95 
execute at @a[lm=96,l=96] run scoreboard players set @p xp 96 
execute at @a[lm=97,l=97] run scoreboard players set @p xp 97 
execute at @a[lm=98,l=98] run scoreboard players set @p xp 98 
execute at @a[lm=99,l=99] run scoreboard players set @p xp 99 
execute at @a[lm=100,l=100] run scoreboard players set @p xp 100 
execute at @a[lm=101,l=101] run scoreboard players set @p xp 101
execute at @a[lm=102,l=102] run scoreboard players set @p xp 102
execute at @a[lm=103,l=103] run scoreboard players set @p xp 103 
execute at @a[lm=104,l=104] run scoreboard players set @p xp 104 
execute at @a[lm=105,l=105] run scoreboard players set @p xp 105
execute at @a[lm=106,l=106] run scoreboard players set @p xp 106
execute at @a[lm=107,l=107] run scoreboard players set @p xp 107 
execute at @a[lm=108,l=108] run scoreboard players set @p xp 108
execute at @a[lm=109,l=109] run scoreboard players set @p xp 109
execute at @a[lm=110,l=110] run scoreboard players set @p xp 110 
execute at @a[lm=111,l=111] run scoreboard players set @p xp 111
execute at @a[lm=112,l=112] run scoreboard players set @p xp 112
execute at @a[lm=113,l=113] run scoreboard players set @p xp 113 
execute at @a[lm=114,l=114] run scoreboard players set @p xp 114
execute at @a[lm=115,l=115] run scoreboard players set @p xp 115
execute at @a[lm=116,l=116] run scoreboard players set @p xp 116 
execute at @a[lm=117,l=117] run scoreboard players set @p xp 117
execute at @a[lm=118,l=118] run scoreboard players set @p xp 118
execute at @a[lm=119,l=119] run scoreboard players set @p xp 119 
execute at @a[lm=120,l=120] run scoreboard players set @p xp 120
execute at @a if score @p xp > "§o§8Bisheriger Rekord " xp run scoreboard players operation "§o§8Bisheriger Rekord " xp = @p xp 